### ISSUE TITLE
Notify users of 3.4.4 via popup

### ISSUE THREAD

**Issue by peteyak** [nsip/hits-dashboard#9]

**Comment by peteyak** [comment]
@peteyak to write text, to implement @scottp

**Comment by peteyak** [comment]
depedent on #10

**Comment by peteyak** [comment]
Text for popup:
" HITS is running SIF data model version <data model version>, SIF infrastructure version <infrastructure version>."

**Comment by Clarinetina** [comment]
Done. Tested by Scott.
